"""Event creation, reduction, projection, and replay primitives."""

from omninode_rsd.lifecycle.authorization import (
    AuthorizationDecisionV1,
    AuthorizationError,
    AuthorizationJournal,
    AuthorizationPaths,
    ProviderProvenance,
    ProviderProvenanceAdapter,
    TrustedEd25519SignerV1,
    authorize,
    consume_authorization,
)
from omninode_rsd.lifecycle.event_log import InMemoryEventLog
from omninode_rsd.lifecycle.ingress import LifecycleEventIngress
from omninode_rsd.lifecycle.models import (
    LifecycleDescription,
    LifecycleEvent,
    LifecycleEventIntent,
    LifecycleEventType,
    LifecycleRunProjection,
    LifecycleState,
    LifecycleTransition,
)
from omninode_rsd.lifecycle.postgres import (
    AppliedLifecycleMigration,
    DurableLifecycleEventLog,
    LifecycleStoreConflictError,
    LifecycleStoreCorruptionError,
    LifecycleStoreError,
    LifecycleStoreTransientError,
    LifecycleStoreUnavailableError,
    MigrationConnectionStateError,
    PostgresConnectionFactory,
    PostgresLifecycleEventLog,
    PostgresLifecycleMigrationRunner,
    PostgresMigrationConnectionFactory,
)
from omninode_rsd.lifecycle.reducer import reduce_lifecycle_event
from omninode_rsd.lifecycle.replay import (
    LifecycleReplay,
    LifecycleReplayArtifactError,
    LifecycleReplayInputError,
    LifecycleReplayMismatchError,
    LifecycleReplayRunMismatchError,
    LifecycleReplayVerificationError,
    replay_lifecycle,
    verify_lifecycle_replay,
)
from omninode_rsd.lifecycle.validation import (
    load_lifecycle_description,
    parse_lifecycle_description,
)

__all__ = [
    "AppliedLifecycleMigration",
    "AuthorizationDecisionV1",
    "AuthorizationError",
    "AuthorizationJournal",
    "AuthorizationPaths",
    "DurableLifecycleEventLog",
    "InMemoryEventLog",
    "LifecycleDescription",
    "LifecycleEvent",
    "LifecycleEventIngress",
    "LifecycleEventIntent",
    "LifecycleEventType",
    "LifecycleReplay",
    "LifecycleReplayArtifactError",
    "LifecycleReplayInputError",
    "LifecycleReplayMismatchError",
    "LifecycleReplayRunMismatchError",
    "LifecycleReplayVerificationError",
    "LifecycleRunProjection",
    "LifecycleState",
    "LifecycleStoreConflictError",
    "LifecycleStoreCorruptionError",
    "LifecycleStoreError",
    "LifecycleStoreTransientError",
    "LifecycleStoreUnavailableError",
    "LifecycleTransition",
    "MigrationConnectionStateError",
    "PostgresConnectionFactory",
    "PostgresLifecycleEventLog",
    "PostgresLifecycleMigrationRunner",
    "PostgresMigrationConnectionFactory",
    "ProviderProvenance",
    "ProviderProvenanceAdapter",
    "TrustedEd25519SignerV1",
    "authorize",
    "consume_authorization",
    "load_lifecycle_description",
    "parse_lifecycle_description",
    "reduce_lifecycle_event",
    "replay_lifecycle",
    "verify_lifecycle_replay",
]
