"""Auditable mapping from the removed V1 disposable suite to V2 behavior.

V2 replaced the pre-live initial-resource contract rather than retaining a
compatibility surface.  This table keeps the security assertions reviewable:
each former test is either exercised by a V2 equivalent or retained in the
generic durable-journal suite.  It is deliberately executable so a future
edit cannot silently shrink the mapping.
"""

from __future__ import annotations

CoverageRow = tuple[str, str, str]


PARENT_DISPOSABLE_COVERAGE: tuple[CoverageRow, ...] = (
    (
        "test_compiles_non_authorizing_value_free_receipt",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_compiles_value_free_non_authorizing_receipt",
    ),
    (
        "test_governed_composite_match_denies_even_on_shared_host",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_governed_collision_blocks",
    ),
    (
        "test_reader_rejects_non_owner_only_artifact",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_reader_rejects_non_owner_only_artifact",
    ),
    (
        "test_content_addressed_overlay_tampering_is_rejected",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_content_addressed_overlay_tampering_blocks",
    ),
    (
        "test_duplicate_yaml_key_is_rejected_before_model_coercion",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_duplicate_yaml_key_blocks_before_model_coercion",
    ),
    (
        "test_candidate_rejects_shared_restore_valkey_volume",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_candidate_rejects_shared_restore_cache_volume",
    ),
    (
        "test_candidate_rejects_service_to_valkey_identity_collision",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_candidate_rejects_service_cache_identity_collision",
    ),
    (
        "test_candidate_rejects_restore_service_published_authority",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_candidate_rejects_restore_service_publication",
    ),
    (
        "test_proposal_rejects_transport_authority_mismatch_with_primary_candidate",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_proposal_rejects_transport_authority_mismatch",
    ),
    (
        "test_proposal_rejects_claimed_loopback_when_candidate_is_tls_lan",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_proposal_rejects_loopback_claim_over_tls_candidate",
    ),
    (
        "test_unpublished_network_transport_rejects_external_address_and_dns",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_unpublished_network_transport_rejects_external_or_dns",
    ),
    (
        "test_proposal_accepts_candidate_bound_internal_network_transport",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_accepts_candidate_bound_internal_network_transport",
    ),
    (
        "test_postgres_identity_requires_positive_oid",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_postgres_identity_requires_positive_oid",
    ),
    (
        "test_final_contract_rejects_postgres_oid_replay_tampering",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_final_contract_rejects_oid_replay_tampering",
    ),
    (
        "test_target_database_oid_and_overlay_oid_are_revalidated",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_target_and_overlay_oid_are_revalidated",
    ),
    (
        "test_provider_snapshot_replay_is_rejected",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_provider_snapshot_epoch_replay_is_rejected",
    ),
    (
        "test_transport_rejects_cleartext_published_lan",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_transport_rejects_cleartext_published_address",
    ),
    (
        "test_cli_blocks_without_creating_artifacts",
        "migrated",
        "tests/lifecycle/test_phase_a_v2_regressions.py::test_phase_a_cli_blocks_without_creating_artifacts",
    ),
    (
        "test_phase_b_executes_only_after_durable_claim",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_allocation_operation_replay_rejects_a_fresh_nonce",
    ),
    (
        "test_initial_intent_is_name_only_and_transport_accepts_no_legacy_alias",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_allocation_intent_excludes_observed_runtime_ids",
    ),
    (
        "test_transition_rejects_cross_intent_and_changed_planned_fields",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_allocation_attestation_binds_exact_effect_and_topology; "
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_materialization_chain_binds_provider_and_allocated_volumes"
        ),
    ),
    (
        "test_initial_scope_cannot_be_used_as_observed_effect_authority",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_allocation_context_is_value_free_and_non_bearer",
    ),
    (
        "test_initial_genesis_reconciliation_never_retries_creation",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_allocation_genesis_crash_leaves_a_terminal_pending_state",
    ),
    (
        "test_external_initial_genesis_blocks_same_operation_at_a_new_path",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_external_allocation_genesis_tombstone_blocks_a_second_local_journal",
    ),
    (
        "test_public_execution_has_no_caller_controlled_clock",
        "retained",
        "tests/lifecycle/test_infisical_disposable.py::test_mutation_boundaries_have_no_caller_clock_or_generic_callback",
    ),
    (
        "test_public_authorization_cannot_rewind_stale_stage_time",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_owner_approval_and_historical_time_block_before_provisioning",
    ),
    (
        "test_phase_b_absent_journal_never_initializes_or_provisions",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_allocation_journal_is_explicit_and_replay_policy_is_durable_first",
    ),
    (
        "test_missing_replay_authority_fails_before_journal_provisioning",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_missing_replay_authority_and_policy_substitution_block_before_claim",
    ),
    (
        "test_initial_replay_policy_is_durable_before_tombstone_and_allows_exact_recovery",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_allocation_journal_is_explicit_and_replay_policy_is_durable_first",
    ),
    (
        "test_initial_replay_policy_substitution_blocks_before_external_claim",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_missing_replay_authority_and_policy_substitution_block_before_claim",
    ),
    (
        "test_observed_genesis_requires_completed_initial_stage_and_durable_replay_policy",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_materialization_journal_requires_committed_allocation_and_never_replays",
    ),
    (
        "test_external_tombstone_blocks_local_rollback_and_deleted_operation_row",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_external_tombstone_blocks_a_local_operation_row_rollback",
    ),
    (
        "test_test_replay_authority_claim_is_atomic_across_processes",
        "retained",
        "tests/lifecycle/test_authorization_journal.py::test_claim_is_atomic_for_threads_and_processes",
    ),
    (
        "test_genesis_blocks_pair_removal_replay_and_identity_file_removal",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_allocation_journal_unknown_or_legacy_local_state_blocks_without_recreation",
    ),
    (
        "test_genesis_copy_or_removal_blocks_effect_before_claim",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_pinned_allocation_journal_identity_blocks_anchor_replacement",
    ),
    (
        "test_genesis_rejects_second_provision_and_signed_mismatch",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_allocation_journal_is_explicit_and_replay_policy_is_durable_first",
    ),
    (
        "test_genesis_crash_windows_require_signed_reconciliation",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_allocation_genesis_crash_leaves_a_terminal_pending_state; "
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_allocation_genesis_crash_after_tombstone_is_not_retried"
        ),
    ),
    (
        "test_phase_b_detects_legacy_journal_before_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_allocation_journal_unknown_or_legacy_local_state_blocks_without_recreation",
    ),
    (
        "test_phase_b_blocks_replaced_journal_before_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_pinned_allocation_journal_identity_blocks_anchor_replacement",
    ),
    (
        "test_phase_b_pins_journal_anchor_before_provider_and_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_pinned_allocation_journal_identity_blocks_anchor_replacement",
    ),
    (
        "test_same_operation_with_fresh_nonce_executes_effect_once",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_allocation_operation_replay_rejects_a_fresh_nonce",
    ),
    (
        "test_effect_failure_requires_recovery_and_never_replays",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_allocation_effect_failure_is_terminal_and_never_replays; "
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_materialization_failure_is_terminal_and_never_replays"
        ),
    ),
    (
        "test_keychain_replay_authority_is_create_only_and_stores_hashes",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_keychain_replay_authority_is_create_only_and_stores_hashes",
    ),
    (
        "test_replay_authority_failure_is_value_redacted_and_prevents_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_replay_authority_errors_are_redacted_and_block_the_claim",
    ),
    (
        "test_provider_and_effect_failures_do_not_expose_adapter_values",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_provider_and_effect_error_text_is_not_exposed_by_safe_boundary; "
            "tests/lifecycle/test_provider_crypto.py::"
            "test_v2_material_genesis_is_create_only_and_partial_state_is_terminal"
        ),
    ),
    (
        "test_owner_lock_rejects_cooperating_artifact_writer_without_waiting",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_artifact_lock_rejects_a_cooperating_thread_without_waiting",
    ),
    (
        "test_owner_lock_rejects_competing_process_without_waiting",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_artifact_lock_rejects_a_competing_process_without_waiting",
    ),
    (
        "test_owner_lock_rejects_recursive_effect_lease",
        "retained",
        "tests/lifecycle/test_infisical_disposable.py::test_artifact_root_lease_rejects_relaxed_mode_symlink_and_recursion",
    ),
    (
        "test_owner_lock_converges_case_variants_on_same_root",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_artifact_lock_converges_case_variants_by_opened_root_identity",
    ),
    (
        "test_phase_b_rejects_root_or_lock_replacement_before_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_artifact_root_replacement_and_lock_unlink_block_stability",
    ),
    (
        "test_recovery_cannot_race_a_live_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_recovery_cannot_race_a_live_allocation_effect",
    ),
    (
        "test_phase_b_refuses_terminal_success_after_lock_changes_during_effect",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_artifact_root_replacement_and_lock_unlink_block_stability; "
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_pinned_allocation_journal_identity_blocks_anchor_replacement"
        ),
    ),
    (
        "test_artifact_lock_rejects_relaxed_mode_and_symlink",
        "retained",
        "tests/lifecycle/test_infisical_disposable.py::test_artifact_root_lease_rejects_relaxed_mode_symlink_and_recursion",
    ),
    (
        "test_phase_b_rejects_artifact_and_provider_mutation_before_effect",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_provider_snapshot_change_is_not_a_stable_provenance_commitment; "
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_artifact_root_replacement_and_lock_unlink_block_stability"
        ),
    ),
    (
        "test_phase_b_rejects_marker_only_signature_and_cli_is_read_only",
        "migrated",
        (
            "tests/lifecycle/test_infisical_disposable.py::"
            "test_v2_sidecar_swap_marker_tamper_and_noncanonical_signature_block; "
            "tests/lifecycle/test_infisical_disposable.py::test_cli_authorize_remains_read_only"
        ),
    ),
    (
        "test_phase_b_rejects_disposal_owner_or_approval_mismatch",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_owner_approval_and_historical_time_block_before_provisioning",
    ),
    (
        "test_external_execution_receipt_cannot_reach_internal_claim",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_forged_allocation_grant_cannot_reach_the_journal",
    ),
    (
        "test_phase_b_rejects_marker_tampering_even_when_phase_a_hashes_are_refreshed",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_sidecar_swap_marker_tamper_and_noncanonical_signature_block",
    ),
    (
        "test_phase_b_rejects_sidecar_swap_and_noncanonical_base64_alias",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_sidecar_swap_marker_tamper_and_noncanonical_signature_block",
    ),
    (
        "test_provider_material_genesis_is_create_only_and_partial_state_blocks_retry",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_material_genesis_is_create_only_and_partial_state_is_terminal",
    ),
    (
        "test_keychain_provenance_adapter_rejects_copied_material_policy",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_copied_provider_material_policy_cannot_cross_allocation_intents",
    ),
    (
        "test_public_material_persistence_cannot_use_a_historical_clock",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_material_policy_uses_the_internal_clock_and_blocks_expired_policy",
    ),
    (
        "test_signer_genesis_binds_keychain_seed_and_refuses_duplicate_creation",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_signer_genesis_is_durable_before_create_only_seed_write",
    ),
    (
        "test_signer_genesis_is_pinned_before_keychain_writes_and_orphans_block",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_provider_artifact_orphan_and_forged_attestation_never_authorize",
    ),
    (
        "test_phase_b_rejects_forged_provider_attestation_before_effect",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_provider_artifact_orphan_and_forged_attestation_never_authorize",
    ),
    (
        "test_phase_b_rejects_manual_provider_without_terminal_material_artifacts",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_pending_material_manifest_cannot_be_used_as_provider_readiness",
    ),
    (
        "test_tls_initial_intent_never_claims_or_reaches_an_effect",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_constructed_tls_type_drift_is_rejected_before_a_mutation_boundary",
    ),
    (
        "test_tls_rejection_has_zero_journal_or_effect_side_effects",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_tls_type_drift_blocks_provisioning_before_root_or_tombstone",
    ),
    (
        "test_tls_cannot_construct_or_load_keychain_signer_or_provider_readiness",
        "migrated",
        "tests/lifecycle/test_provider_crypto.py::test_v2_tls_drift_cannot_construct_or_load_provider_readiness",
    ),
    (
        "test_tls_type_drift_is_blocked_before_replay_or_keychain_creation",
        "migrated",
        "tests/lifecycle/test_infisical_disposable.py::test_v2_tls_type_drift_blocks_provisioning_before_root_or_tombstone",
    ),
)


def test_v2_coverage_mapping_accounts_for_every_parent_disposable_test() -> None:
    """Keep the replacement suite complete without restoring V1 APIs or aliases."""

    assert len(PARENT_DISPOSABLE_COVERAGE) == 70
    names = tuple(row[0] for row in PARENT_DISPOSABLE_COVERAGE)
    assert len(set(names)) == len(names)
    assert all(
        disposition in {"migrated", "retained", "retired"}
        for _, disposition, _ in PARENT_DISPOSABLE_COVERAGE
    )
    assert all(target.startswith("tests/") for _, _, target in PARENT_DISPOSABLE_COVERAGE)
